[package]
name = "viav"
version = "0.1.0"
authors = ["Brandon Dyer <BrandonDyer64@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.6.0-rc.1"

[replace."openssl:0.9.37"]
git = "https://github.com/kryptco/rust-openssl"
